SELECT
        f.fdc_id,
        f.description,
        f.food_category_id
    FROM {table_name} f
    WHERE (f.food_category_id NOT IN (1, 3, 5, 7, 10, 13, 15, 17, 21, 22, 24, 25, 27)
        AND ((f.description NOT LIKE '%chicken%')
        AND (f.description NOT LIKE '%beef%')
        AND (f.description NOT LIKE '%clam%')
        AND (f.description NOT LIKE '%steak%')
        AND (f.description NOT LIKE '%pork%')
        AND (f.description NOT LIKE '%bacon%')
        AND (f.description NOT LIKE '% ham%')
        AND (f.description NOT LIKE '%pepperoni%')
        AND (f.description NOT LIKE '%salami%')
        AND (f.description NOT LIKE '%jerky%')
        AND (f.description NOT LIKE '%lamb%')
        AND (f.description NOT LIKE '%turkey%')
        AND (f.description NOT LIKE '%duck%')
        AND (f.description NOT LIKE '%goose%')
        AND (f.description NOT LIKE '%quail%')
        AND (f.description NOT LIKE '%giblet%')
        AND (f.description NOT LIKE '%salmon%')
        AND (f.description NOT LIKE '%tuna%')
        AND (f.description NOT LIKE '%shrimp%')
        AND (f.description NOT LIKE '%prawn%')
        AND (f.description NOT LIKE '%crab%')
        AND (f.description NOT LIKE '%lobster%')
        AND (f.description NOT LIKE '%anchovy%')
        AND (f.description NOT LIKE '%sardine%')
        AND (f.description NOT LIKE '%scallop%')
        AND (f.description NOT LIKE '%oyster%')
        AND (f.description NOT LIKE '%mussel%')
        AND (f.description NOT LIKE '%milk%')
        AND (f.description NOT LIKE '%cheese%')
	AND (f.description NOT LIKE '%cheddar%')
	AND (f.description NOT LIKE '%mozzarella%')
	AND (f.description NOT LIKE '%parmesan%')
	AND (f.description NOT LIKE '%swiss%')
	AND (f.description NOT LIKE '%provolone%')
        AND (f.description NOT LIKE '%butter%')
        AND (f.description NOT LIKE '%cream%')
        AND (f.description NOT LIKE '%yogurt%')
        AND (f.description NOT LIKE '%whey%')
        AND (f.description NOT LIKE '%casein%')
        AND (f.description NOT LIKE '%lactose%')
        AND (f.description NOT LIKE '%ghee%')
        AND (f.description NOT LIKE '%custard%')
        AND (f.description NOT LIKE '%kefir%')
        AND (f.description NOT LIKE '%egg%')
        AND (f.description NOT LIKE '%honey%')
        AND (f.description NOT LIKE '%beeswax%')
        AND (f.description NOT LIKE '%gelatin%')
        AND (f.description NOT LIKE '%collagen%')
        AND (f.description NOT LIKE '%lard%')
        AND (f.description NOT LIKE '%tallow%')
        AND (f.description NOT LIKE '%suet%')
        AND (f.description NOT LIKE '%drippings%')
        AND (f.description NOT LIKE '%bone%')
        AND (f.description NOT LIKE '%fish%')
        AND (f.description NOT LIKE '%seafood%')
        AND (f.description NOT LIKE '% cod%')
        AND (f.description NOT LIKE '%tilapia%')
        AND (f.description NOT LIKE '%catfish%')
        AND (f.description NOT LIKE '%herring%')
        AND (f.description NOT LIKE '%mackerel%')
        AND (f.description NOT LIKE '%trout%')
        AND (f.description NOT LIKE '%halibut%')
        AND (f.description NOT LIKE '%flounder%')
        AND (f.description NOT LIKE '%mahi%')
        AND (f.description NOT LIKE '%eel%')
        AND (f.description NOT LIKE '%octopus%')
        AND (f.description NOT LIKE '%squid%')
        AND (f.description NOT LIKE '%caviar%')
        AND (f.description NOT LIKE '%roe%')
        AND (f.description NOT LIKE '%seafood%')
        AND (f.description NOT LIKE '% cod%')
        AND (f.description NOT LIKE '%tilapia%')
        AND (f.description NOT LIKE '%catfish%')
        AND (f.description NOT LIKE '%herring%')
        AND (f.description NOT LIKE '%mackerel%')
        AND (f.description NOT LIKE '%trout%')
        AND (f.description NOT LIKE '%halibut%')
        AND (f.description NOT LIKE '%flounder%')
        AND (f.description NOT LIKE '%mahi%')
        AND (f.description NOT LIKE '%eel%')
        AND (f.description NOT LIKE '%octopus%')
        AND (f.description NOT LIKE '%squid%')
        AND (f.description NOT LIKE '%caviar%')
        AND (f.description NOT LIKE '%roe%')
	AND (f.description NOT LIKE '%gummy%')
	AND (f.description NOT LIKE '%chocolate%' OR f.description LIKE '%dark%')
	AND (f.description NOT LIKE '%creme%')
	)
	OR (f.food_category_id IN (11, 16, 39))
	OR (f.description LIKE '%plant%based%')
	OR (f.description LIKE '%meatless%')
	OR (f.description LIKE '%vegan%'))
	OR (f.description LIKE '%dairy%free%')
	OR (f.description LIKE '%non-dairy%')
	AND f.fdc_id NOT IN (
		SELECT fdc_id
		FROM food_nutrient
		WHERE nutrient_id = 1253 AND amount > 0
	)
